<x-mail::message>
# File Control Sheet Report

**Application:** {{ $application->business_name }}
**Application ID:** #{{ $application->id }}

@if($customMessage)
{{ $customMessage }}

---
@endif

Please find attached the File Control Sheet (FCS) report for the above application.

## Summary

| Metric | Value |
|:-------|------:|
| True Revenue | ${{ number_format($application->documents()->where('document_type', 'bank_statement')->whereNotNull('true_revenue')->sum('true_revenue'), 2) }} |
| Underwriting Score | {{ $application->underwriting_score ?? 'N/A' }}/100 |
| Decision | {{ str_replace('_', ' ', $application->underwriting_decision ?? 'N/A') }} |

@if($application->underwriting_score)
@php
$uwLevel = $application->underwriting_score >= 75 ? 'Approve' : ($application->underwriting_score >= 45 ? 'Review Recommended' : 'High Risk');
@endphp
**Recommendation:** {{ $uwLevel }}
@endif

<x-mail::button :url="route('applications.show', $application)">
View Application
</x-mail::button>

This report was automatically generated by the CRMfinity underwriting system.

Thanks,<br>
{{ config('app.name') }}
</x-mail::message>
